apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate-job
spec:
  backoffLimit: 2
  activeDeadlineSeconds: 60
  ttlSecondsAfterFinished: 60
  template:
    spec:
      containers:
      - name : djangoapp-migrate
        image: sadrus/k8s_djangoapp:latest
        envFrom:
          - configMapRef:
              name: django-config
        imagePullPolicy: IfNotPresent
        command:
          - python
          - manage.py
          - migrate
        args:
          - --no-input
      restartPolicy: Never