version: "3"

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB-test_k8}
      POSTGRES_USER: ${POSTGRES_USER-test_k8}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-OwOtBep9Frut}
networks:
  default:
    external:
      name: minikube
volumes:
  db_data:
